name: NodeJS

# Evento que inicializa el flujo de CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag node-app
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: API Test
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm ci
      - run: npm test
