name: NodeJS

# Evento que inicializa el flujo de CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login al Heroku Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build & push de mi imagen
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          docker build . --tag docker -f Dockerfile
          docker tag docker registry.heroku.com/${{ secrets.HEROKU_APP_NAME  }}/web
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME  }}/web
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: API Test
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm ci
      - run: npm test
